### ISSUE TITLE
Build out CRUD api

### ISSUE THREAD

**Issue by xynree** [xynree/rating-room-r#10]

**Comment by zschaffer** [comment]
Should `create_item` concern itself with a category and rating or should we have seperate functions for adding a rating/category to an item? should a user be able to create an item without immediately associating a category and/or a rating to it? @xynree

**Comment by xynree** [comment]
> Should `create_item` concern itself with a category and rating or should we have seperate functions for adding a rating/category to an item? should a user be able to create an item without immediately associating a category and/or a rating to it? @xynree

Categories are meant to be optionally added, while ratings are meant to be "required". We can allow users to not enter in a rating but I think it'd be best to store it as `0` rather than allowing `None`. Categories should be okay to have `None`.

**Comment by zschaffer** [comment]
so `create_item` func sig could be something like
```rust
fn create_item(state: State<AppState>, item: Item, rating: Option<Rating>, category: Option<Category>)
```
and we can just check for None in rating and set it to `0`, and leave category empty
